"""Sincronizacion inicial

Revision ID: 4f5645e89dd0
Revises: 
Create Date: 2026-01-18 21:57:47.120324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5645e89dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index('idx_asistencia_busqueda', ['estudiante_id', 'materia_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('asistencias_estudiante_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('asistencias_materia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['estudiante_id'], ['id'])

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inscripciones_estudiante_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('inscripciones_materia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['estudiante_id'], ['id'])
        batch_op.create_foreign_key(None, 'materias', ['materia_id'], ['id'])

    with op.batch_alter_table('solicitud_clave', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitud_clave_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('solicitudes_recuperacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_recuperacion_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_cedula_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_cedula'), ['cedula'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_cedula'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('solicitudes_recuperacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_recuperacion_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitud_clave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitud_clave_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inscripciones_materia_id_fkey'), 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('inscripciones_estudiante_id_fkey'), 'usuarios', ['estudiante_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asistencias_materia_id_fkey'), 'materias', ['materia_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('asistencias_estudiante_id_fkey'), 'usuarios', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('idx_asistencia_busqueda')

    # ### end Alembic commands ###
